export const SV_MATRIX_FIXTURE_ROOT = "packages/fixtures/packages/sv-matrix/items";

export const itemPath = (id: string): string => `${SV_MATRIX_FIXTURE_ROOT}/${id}.xml`;
export const player = "qti-assessment-item-player";
export const choice = `${player} .qti3-choice`;
export const choiceA = `${choice} .qti3-choice-option[data-choice-identifier="A"]`;
export const choiceB = `${choice} .qti3-choice-option[data-choice-identifier="B"]`;
export const choiceLabels = `${choice} .qti3-choice-label`;
export const choiceList = `${choice} .qti3-choice-list`;
export const orderLayout = `${player} .qti3-order-sv-layout`;
export const orderBank = `${orderLayout} .qti3-order-choices-bank`;
export const orderTargets = `${orderLayout} .qti3-order-target-list`;
export const orderRoot = `${player} .qti3-order`;
export const orderLabels = `${orderTargets} .qti3-order-target-label`;
export const minOrderRoot = `${player} [data-response-identifier="MIN_RESPONSE"]`;
export const minOrderBank = `${minOrderRoot} .qti3-order-choices-bank`;
export const minOrderAHandle = `${minOrderRoot} .qti3-order-target-item[data-choice-identifier="A"] .qti3-reorder-handle`;
export const maxOrderRoot = `${player} [data-response-identifier="MAX_RESPONSE"]`;
export const maxOrderBank = `${maxOrderRoot} .qti3-order-choices-bank`;
export const maxOrderAHandle = `${maxOrderRoot} .qti3-order-target-item[data-choice-identifier="A"] .qti3-reorder-handle`;
export const extendedText = `${player} .qti3-extendedText`;
export const matchLayout = `${player} .qti3-match-selector`;
export const matchRoot = `${player} .qti3-match`;
export const matchBank = `${matchLayout} .qti3-match-source-bank`;
export const matchTargets = `${matchLayout} .qti3-match-target-bank`;
export const gapLayout = `${player} .qti3-gap-match-layout`;
export const gapRoot = `${player} .qti3-gapMatch`;
export const gapBank = `${gapLayout} .qti3-gap-source-region`;
export const gapTargets = `${gapLayout} .qti3-gap-region`;
export const standaloneTextWidth4 = `${player} [data-response-identifier="BLOCK_4"] input.qti3-text-input`;
export const standaloneTextWidth20 = `${player} [data-response-identifier="BLOCK_20"] input.qti3-text-input`;
export const bodyTextWidth4 = `${player} [data-response-identifier="BODY_4"] input.qti3-inline-text-input`;
export const bodyTextWidth20 = `${player} [data-response-identifier="BODY_20"] input.qti3-inline-text-input`;
export const inlineTextWidth4 = `${player} [data-response-identifier="INLINE_4"] input.qti3-inline-text-input`;
export const inlineTextWidth20 = `${player} [data-response-identifier="INLINE_20"] input.qti3-inline-text-input`;
export const inlineChoiceWidth4 = `${player} [data-response-identifier="CHOICE_4"] .qti3-inline-choice-control`;
export const inlineChoiceWidth20 = `${player} [data-response-identifier="CHOICE_20"] .qti3-inline-choice-control`;
export const inlineChoiceVerticalRoot = `${player} [data-response-identifier="RESPONSE"].qti3-inlineChoice`;
export const inlineChoiceVerticalControl = `${inlineChoiceVerticalRoot} .qti3-inline-choice-control`;
export const graphicGapRoot = `${player} .qti3-graphicGapMatch`;
export const graphicGapLayout = `${player} .qti3-graphic-gap-layout`;
export const graphicGapBank = `${graphicGapLayout} .qti3-graphic-gap-source-region`;
export const graphicGapSurface = `${graphicGapLayout} .qti3-graphic-gap-match-surface`;
export const graphicGapHotspotT1 = `${graphicGapRoot} .qti3-graphic-gap-hotspot[data-gap-identifier="T1"]`;
export const graphicGapHotspotT2 = `${graphicGapRoot} .qti3-graphic-gap-hotspot[data-gap-identifier="T2"]`;
export const graphicGapSourceA = `${graphicGapBank} button[data-choice-identifier="A"]`;
export const hottextRoot = `${player} .qti3-hottext`;
export const hottextA = `${hottextRoot} .qti3-hottext-token[data-choice-identifier="A"]`;
export const hottextB = `${hottextRoot} .qti3-hottext-token[data-choice-identifier="B"]`;
export const hottextAVisibleText = `${hottextA} + .qti3-hottext-visible-text`;
export const hottextBVisibleText = `${hottextB} + .qti3-hottext-visible-text`;
export const inputWidths = [1, 2, 3, 4, 6, 10, 15, 20, 25, 30, 35, 40, 45, 50, 72] as const;
export const itemBody = `${player} .qti3-item-body`;
