import type { SharedVocabularyManifestEntry } from "./types.js";
import {
  bodyTextWidth4,
  bodyTextWidth20,
  choice,
  choiceA,
  choiceB,
  choiceLabels,
  choiceList,
  extendedText,
  gapBank,
  gapLayout,
  gapRoot,
  gapTargets,
  graphicGapBank,
  graphicGapLayout,
  graphicGapRoot,
  graphicGapSurface,
  hottextA,
  hottextAVisibleText,
  hottextB,
  hottextBVisibleText,
  hottextRoot,
  inlineChoiceWidth4,
  inlineChoiceWidth20,
  inlineTextWidth4,
  inlineTextWidth20,
  inputWidths,
  matchBank,
  matchLayout,
  matchRoot,
  matchTargets,
  maxOrderAHandle,
  maxOrderBank,
  minOrderAHandle,
  minOrderBank,
  orderBank,
  orderLabels,
  orderLayout,
  orderRoot,
  orderTargets,
  player,
  standaloneTextWidth4,
  standaloneTextWidth20,
} from "./manifest-selectors.js";
import {
  choiceStackingAssertions,
  choicesPositionAssertions,
  classNames,
  entry,
  graphicGapSelectionAssertions,
  interactionInputWidthPairAssertions,
  labelAssertions,
  labelStyleCases,
  labelSuffixCases,
  selectionAssertions,
} from "./manifest-helpers.js";
import { contentManifestEntries } from "./manifest-entries-content.js";

const interactionManifestEntries: SharedVocabularyManifestEntry[] = [
  entry("choice-selections-dark", "choice", "qti-selections-dark", "stylesheet", [
    { type: "class-preserved", selector: choice, className: "qti-selections-dark" },
    {
      type: "computed-style-not",
      selector: choiceB,
      property: "background-color",
      value: "rgba(0, 0, 0, 0)",
    },
    { type: "click", selector: `${choiceA} input` },
    {
      type: "computed-style-differs",
      firstSelector: choiceA,
      secondSelector: choiceB,
      property: "background-color",
    },
    {
      type: "computed-style-differs",
      firstSelector: choiceA,
      secondSelector: choiceB,
      property: "color",
    },
    {
      type: "computed-style-differs",
      firstSelector: choiceA,
      secondSelector: choiceB,
      property: "opacity",
    },
  ]),
  entry(
    "choice-selections-light-forced-colors",
    "choice",
    "qti-selections-light",
    "stylesheet",
    selectionAssertions("qti-selections-light"),
    { forcedColors: true },
  ),
  entry(
    "choice-selections-dark-forced-colors",
    "choice",
    "qti-selections-dark",
    "stylesheet",
    selectionAssertions("qti-selections-dark"),
    { forcedColors: true },
  ),
  entry("choice-unselected-hidden", "choice", "qti-unselected-hidden", "stylesheet", [
    { type: "class-preserved", selector: choice, className: "qti-unselected-hidden" },
    {
      type: "computed-style-number",
      selector: choiceA,
      property: "opacity",
      comparison: "less-than",
      value: 1,
    },
    { type: "focus", selector: `${choiceA} input` },
    { type: "key", key: "Tab" },
    {
      type: "computed-style-number",
      selector: choiceB,
      property: "opacity",
      comparison: "greater-than-or-equal",
      value: 1,
    },
    { type: "key", key: "Space" },
    { type: "attribute", selector: choiceB, name: "data-selected", value: "true" },
    {
      type: "computed-style-number",
      selector: choiceB,
      property: "opacity",
      comparison: "greater-than-or-equal",
      value: 1,
    },
  ]),
  entry("hottext-unselected-hidden", "hottext", "qti-unselected-hidden", "stylesheet", [
    { type: "class-preserved", selector: hottextRoot, className: "qti-unselected-hidden" },
    {
      type: "computed-style",
      selector: hottextA,
      property: "border-top-color",
      value: "rgba(0, 0, 0, 0)",
    },
    {
      type: "computed-style",
      selector: hottextA,
      property: "text-decoration-color",
      value: "rgba(0, 0, 0, 0)",
    },
    { type: "focus", selector: hottextA },
    {
      type: "computed-style-not",
      selector: hottextA,
      property: "border-top-color",
      value: "rgba(0, 0, 0, 0)",
    },
    { type: "key", key: "Tab" },
    {
      type: "computed-style-not",
      selector: hottextB,
      property: "border-top-color",
      value: "rgba(0, 0, 0, 0)",
    },
    { type: "key", key: "Space" },
    { type: "attribute", selector: hottextB, name: "data-selected", value: "true" },
  ]),
  entry("hottext-input-control-hidden", "hottext", "qti-input-control-hidden", "stylesheet", [
    { type: "class-preserved", selector: hottextRoot, className: "qti-input-control-hidden" },
    {
      type: "element-count",
      selector: `${hottextRoot} .qti3-hottext-visible-text`,
      count: 2,
    },
    {
      type: "dom-order",
      firstSelector: hottextA,
      secondSelector: hottextAVisibleText,
      order: "before",
    },
    { type: "hidden-focusable-input", selector: hottextA },
    { type: "focus", selector: hottextA },
    {
      type: "computed-style-not",
      selector: hottextAVisibleText,
      property: "outline-style",
      value: "none",
    },
    { type: "click", selector: hottextB },
    { type: "attribute", selector: hottextB, name: "data-selected", value: "true" },
    {
      type: "computed-style-not",
      selector: hottextBVisibleText,
      property: "background-color",
      value: "rgba(0, 0, 0, 0)",
    },
  ]),
  entry(
    "hottext-input-control-unselected-hidden",
    "hottext",
    ["qti-input-control-hidden", "qti-unselected-hidden"],
    "stylesheet",
    [
      { type: "class-preserved", selector: hottextRoot, className: "qti-input-control-hidden" },
      { type: "class-preserved", selector: hottextRoot, className: "qti-unselected-hidden" },
      {
        type: "element-count",
        selector: `${hottextRoot} .qti3-hottext-visible-text`,
        count: 2,
      },
      {
        type: "computed-style",
        selector: hottextAVisibleText,
        property: "text-decoration-line",
        value: "none",
      },
      { type: "hidden-focusable-input", selector: hottextA },
      { type: "focus", selector: hottextA },
      {
        type: "computed-style-not",
        selector: hottextAVisibleText,
        property: "outline-style",
        value: "none",
      },
      { type: "key", key: "Tab" },
      {
        type: "computed-style-not",
        selector: hottextBVisibleText,
        property: "outline-style",
        value: "none",
      },
      { type: "key", key: "Space" },
      { type: "attribute", selector: hottextB, name: "data-selected", value: "true" },
      {
        type: "computed-style-not",
        selector: hottextBVisibleText,
        property: "background-color",
        value: "rgba(0, 0, 0, 0)",
      },
    ],
  ),
  entry(
    "choice-stacking-vertical",
    "choice",
    ["qti-choices-stacking-3", "qti-orientation-vertical"],
    "full",
    [
      { type: "class-preserved", selector: choice, className: "qti-choices-stacking-3" },
      { type: "class-preserved", selector: choice, className: "qti-orientation-vertical" },
      {
        type: "attribute",
        selector: `${choice} .qti3-choice-list`,
        name: "data-qti-orientation",
        value: "vertical",
      },
      {
        type: "attribute",
        selector: `${choice} .qti3-choice-list`,
        name: "data-qti-stacking",
        value: "3",
      },
      {
        type: "computed-style",
        selector: `${choice} .qti3-choice-list`,
        property: "grid-auto-flow",
        value: "column",
      },
    ],
  ),
  entry(
    "choice-stacking-1-horizontal",
    "choice",
    ["qti-choices-stacking-1", "qti-orientation-horizontal"],
    "full",
    choiceStackingAssertions(
      ["qti-choices-stacking-1", "qti-orientation-horizontal"],
      1,
      "horizontal",
    ),
  ),
  entry(
    "choice-stacking-2",
    "choice",
    "qti-choices-stacking-2",
    "full",
    choiceStackingAssertions("qti-choices-stacking-2", 2),
  ),
  entry(
    "choice-stacking-4",
    "choice",
    "qti-choices-stacking-4",
    "full",
    choiceStackingAssertions("qti-choices-stacking-4", 4),
  ),
  entry(
    "choice-stacking-5",
    "choice",
    "qti-choices-stacking-5",
    "full",
    choiceStackingAssertions("qti-choices-stacking-5", 5),
  ),
  entry("choice-input-control-hidden", "choice", "qti-input-control-hidden", "stylesheet", [
    { type: "class-preserved", selector: choice, className: "qti-input-control-hidden" },
    { type: "hidden-focusable-input", selector: `${choiceA} input` },
  ]),
  entry(
    "choice-writing-orientation-vertical-rl",
    "choice",
    "qti-writing-orientation-vertical-rl",
    "stylesheet",
    [
      {
        type: "class-preserved",
        selector: choice,
        className: "qti-writing-orientation-vertical-rl",
      },
      {
        type: "computed-style",
        selector: choiceList,
        property: "writing-mode",
        value: "vertical-rl",
      },
      {
        type: "computed-style",
        selector: `${choice} .qti3-choice-label`,
        property: "text-orientation",
        value: "upright",
      },
    ],
  ),
  ...[...labelStyleCases, ...labelSuffixCases].map((item) =>
    entry(
      `choice-${item.id}`,
      "choice",
      item.className,
      "full",
      labelAssertions(
        choice,
        choiceLabels,
        [1, 2, 3].map(
          (index) => `${choice} .qti3-choice-option:nth-child(${index}) .qti3-choice-label`,
        ),
        item.className,
        item.expected,
      ),
    ),
  ),
  entry("order-choices-left-width", "order", "qti-choices-left", "full", [
    { type: "class-preserved", selector: `${player} .qti3-order`, className: "qti-choices-left" },
    { type: "attribute", selector: orderLayout, name: "data-qti-choices-position", value: "left" },
    { type: "dom-order", firstSelector: orderBank, secondSelector: orderTargets, order: "before" },
    { type: "layout-width", selector: orderBank, expected: 180, tolerance: 4 },
    {
      type: "position",
      firstSelector: orderBank,
      secondSelector: orderTargets,
      axis: "x",
      relation: "less-than",
    },
  ]),
  entry("order-orientation-vertical", "order", "qti-orientation-vertical", "full", [
    {
      type: "class-preserved",
      selector: `${player} .qti3-order`,
      className: "qti-orientation-vertical",
    },
    {
      type: "attribute",
      selector: orderLayout,
      name: "data-qti-order-orientation",
      value: "vertical",
    },
    { type: "computed-style", selector: orderBank, property: "flex-direction", value: "column" },
  ]),
  ...[...labelStyleCases, ...labelSuffixCases].map((item) => {
    const orderClasses = [...classNames(item.className), "qti-choices-top"];
    return entry(
      `order-${item.id}`,
      "order",
      orderClasses,
      "full",
      labelAssertions(
        orderRoot,
        orderLabels,
        [1, 2, 3].map(
          (index) =>
            `${orderTargets} .qti3-order-target-slot:nth-child(${index}) .qti3-order-target-label`,
        ),
        orderClasses,
        item.expected,
      ),
    );
  }),
  entry(
    "order-min-max-messages",
    "order",
    ["data-min-selections-message", "data-max-selections-message"],
    "full",
    [
      // MIN_RESPONSE: one choice placed, score blocked with custom minimum message.
      { type: "click", selector: `${minOrderBank} button[data-choice-identifier="A"]` },
      {
        type: "validation-message",
        responseIdentifier: "MIN_RESPONSE",
        controlSelector: minOrderAHandle,
        message: "Place at least two steps",
      },
      { type: "click", selector: `${minOrderBank} button[data-choice-identifier="B"]` },
      {
        type: "validation-message",
        responseIdentifier: "MIN_RESPONSE",
        controlSelector: minOrderAHandle,
        message: "Place at least two steps",
        expectInvalid: false,
      },
      // MAX_RESPONSE: three choices placed, score blocked with custom maximum message.
      { type: "click", selector: `${maxOrderBank} button[data-choice-identifier="A"]` },
      { type: "click", selector: `${maxOrderBank} button[data-choice-identifier="B"]` },
      { type: "click", selector: `${maxOrderBank} button[data-choice-identifier="C"]` },
      {
        type: "validation-message",
        responseIdentifier: "MAX_RESPONSE",
        controlSelector: maxOrderAHandle,
        message: "Place no more than two steps",
      },
    ],
  ),
  entry(
    "gap-input-width-variants",
    "gapMatch",
    inputWidths.map((width) => `qti-input-width-${width}`),
    "full",
    inputWidths.map(
      (width): SharedVocabularyAssertion => ({
        type: "attribute",
        selector: `${player} [data-gap-identifier="G${width}"]`,
        name: "data-qti-gap-input-width",
        value: String(width),
      }),
    ),
  ),
  entry(
    "interaction-input-width-standalone",
    "textEntry",
    ["qti-input-width-4", "qti-input-width-20"],
    "full",
    interactionInputWidthPairAssertions(standaloneTextWidth4, standaloneTextWidth20),
  ),
  entry(
    "interaction-input-width-embedded",
    "textEntry",
    ["qti-input-width-4", "qti-input-width-20"],
    "full",
    [
      ...interactionInputWidthPairAssertions(bodyTextWidth4, bodyTextWidth20),
      ...interactionInputWidthPairAssertions(inlineTextWidth4, inlineTextWidth20),
      ...interactionInputWidthPairAssertions(inlineChoiceWidth4, inlineChoiceWidth20),
    ],
  ),
  entry(
    "text-entry-pattern-mask-inline",
    "textEntry",
    ["pattern-mask", "data-patternmask-message"],
    "full",
    [
      {
        type: "attribute",
        selector: `${player} [data-response-identifier="RESPONSE"] input.qti3-inline-text-input`,
        name: "placeholder",
        value: "000",
      },
      {
        type: "text",
        selector: `${player} .qti3-inline-text-response .qti3-pattern-mask-message`,
        value: "Maximum of 3 digits permitted",
      },
    ],
  ),
  entry(
    "extendedtext-height-counter-variants",
    "extendedText",
    [
      "qti-height-lines-3",
      "qti-height-lines-6",
      "qti-height-lines-15",
      "qti-counter-up",
      "qti-counter-down",
    ],
    "full",
    [
      {
        type: "class-preserved",
        selector: `${extendedText}[data-response-identifier="LINES3"]`,
        className: "qti-height-lines-3",
      },
      {
        type: "attribute",
        selector: `${extendedText}[data-response-identifier="LINES3"] textarea`,
        name: "rows",
        value: "3",
      },
      {
        type: "class-preserved",
        selector: `${extendedText}[data-response-identifier="LINES6"]`,
        className: "qti-height-lines-6",
      },
      {
        type: "attribute",
        selector: `${extendedText}[data-response-identifier="LINES6"] textarea`,
        name: "rows",
        value: "6",
      },
      {
        type: "class-preserved",
        selector: `${extendedText}[data-response-identifier="LINES15"]`,
        className: "qti-height-lines-15",
      },
      {
        type: "attribute",
        selector: `${extendedText}[data-response-identifier="LINES15"] textarea`,
        name: "rows",
        value: "15",
      },
      {
        type: "class-preserved",
        selector: `${extendedText}[data-response-identifier="COUNTER_UP"]`,
        className: "qti-counter-up",
      },
      {
        type: "class-preserved",
        selector: `${extendedText}[data-response-identifier="COUNTER_UP"] .qti3-text-response > :first-child`,
        className: "qti3-counter",
      },
      {
        type: "class-preserved",
        selector: `${extendedText}[data-response-identifier="COUNTER_DOWN"]`,
        className: "qti-counter-down",
      },
      {
        type: "class-preserved",
        selector: `${extendedText}[data-response-identifier="COUNTER_DOWN"] .qti3-text-response > :last-child`,
        className: "qti3-counter",
      },
    ],
  ),
  entry(
    "extended-text-pattern-mask",
    "extendedText",
    ["pattern-mask", "data-patternmask-message"],
    "full",
    [
      {
        type: "attribute",
        selector: `${extendedText}[data-response-identifier="RESPONSE"] textarea`,
        name: "placeholder",
        value: "Enter a decimal number...",
      },
      {
        type: "text",
        selector: `${extendedText}[data-response-identifier="RESPONSE"] .qti3-pattern-mask-message`,
        value: "Maximum of 6 digits or decimal points permitted",
      },
    ],
  ),
  entry(
    "media-controls-and-pause",
    "media",
    [
      "data-qti-media-player-controls",
      "data-qti-media-player-pause-delay",
      "data-qti-media-player-pause-duration",
    ],
    "full",
    [
      {
        type: "attribute",
        selector: `${player} audio[data-qti-media-player-controls="none"]`,
        name: "data-qti-media-player-controls",
        value: "none",
      },
      {
        type: "attribute-absent",
        selector: `${player} audio[data-qti-media-player-controls="none"]`,
        name: "controls",
      },
      {
        type: "attribute",
        selector: `${player} audio[data-qti-media-player-controls="default"]`,
        name: "data-qti-media-player-controls",
        value: "default",
      },
      {
        type: "attribute",
        selector: `${player} audio[data-qti-media-player-controls="default"]`,
        name: "controls",
        value: "",
      },
      {
        type: "attribute",
        selector: `${player} audio[data-qti-media-player-pause-delay="0.02"]`,
        name: "data-qti-media-player-pause-delay",
        value: "0.02",
      },
      {
        type: "attribute",
        selector: `${player} audio[data-qti-media-player-pause-duration="0.03"]`,
        name: "data-qti-media-player-pause-duration",
        value: "0.03",
      },
    ],
  ),
  entry(
    "match-choices-top",
    "match",
    "qti-choices-top",
    "full",
    choicesPositionAssertions({
      interactionRoot: matchRoot,
      layoutSelector: matchLayout,
      bankSelector: matchBank,
      targetSelector: matchTargets,
      position: "top",
      className: "qti-choices-top",
    }),
  ),
  entry(
    "match-choices-bottom",
    "match",
    "qti-choices-bottom",
    "full",
    choicesPositionAssertions({
      interactionRoot: matchRoot,
      layoutSelector: matchLayout,
      bankSelector: matchBank,
      targetSelector: matchTargets,
      position: "bottom",
      className: "qti-choices-bottom",
    }),
  ),
  entry(
    "match-choices-left",
    "match",
    "qti-choices-left",
    "full",
    choicesPositionAssertions({
      interactionRoot: matchRoot,
      layoutSelector: matchLayout,
      bankSelector: matchBank,
      targetSelector: matchTargets,
      position: "left",
      className: "qti-choices-left",
    }),
  ),
  entry(
    "match-choices-right",
    "match",
    "qti-choices-right",
    "full",
    choicesPositionAssertions({
      interactionRoot: matchRoot,
      layoutSelector: matchLayout,
      bankSelector: matchBank,
      targetSelector: matchTargets,
      position: "right",
      className: "qti-choices-right",
    }),
  ),
  entry("match-tabular-first-column-header", "match", "qti-match-tabular", "full", [
    { type: "class-preserved", selector: matchRoot, className: "qti-match-tabular" },
    {
      type: "text",
      selector: `${player} .qti3-match-table thead th:first-child`,
      value: "Characters",
    },
    {
      type: "text",
      selector: `${player} .qti3-match-table tbody tr:first-child th`,
      value: "Capulet.",
    },
  ]),
  entry(
    "match-tabular-header-hidden",
    "match",
    ["qti-match-tabular", "qti-header-hidden"],
    "conditional",
    [
      { type: "class-preserved", selector: matchRoot, className: "qti-match-tabular" },
      {
        type: "class-preserved",
        selector: `${player} .qti3-match-table`,
        className: "qti-header-hidden",
      },
      { type: "element-count", selector: `${player} .qti3-match-table thead`, count: 0 },
      {
        type: "text",
        selector: `${player} .qti3-match-table tbody tr:first-child th`,
        value: "Capulet",
      },
      {
        type: "attribute",
        selector: `${player} .qti3-match-table-cell`,
        name: "aria-label",
        value: "Capulet to Romeo and Juliet",
      },
    ],
  ),
  entry(
    "gap-choices-top",
    "gapMatch",
    "qti-choices-top",
    "full",
    choicesPositionAssertions({
      interactionRoot: gapRoot,
      layoutSelector: gapLayout,
      bankSelector: gapBank,
      targetSelector: gapTargets,
      position: "top",
      className: "qti-choices-top",
    }),
  ),
  entry(
    "gap-choices-bottom",
    "gapMatch",
    "qti-choices-bottom",
    "full",
    choicesPositionAssertions({
      interactionRoot: gapRoot,
      layoutSelector: gapLayout,
      bankSelector: gapBank,
      targetSelector: gapTargets,
      position: "bottom",
      className: "qti-choices-bottom",
    }),
  ),
  entry(
    "gap-choices-left",
    "gapMatch",
    "qti-choices-left",
    "full",
    choicesPositionAssertions({
      interactionRoot: gapRoot,
      layoutSelector: gapLayout,
      bankSelector: gapBank,
      targetSelector: gapTargets,
      position: "left",
      className: "qti-choices-left",
    }),
  ),
  entry(
    "gap-choices-right",
    "gapMatch",
    "qti-choices-right",
    "full",
    choicesPositionAssertions({
      interactionRoot: gapRoot,
      layoutSelector: gapLayout,
      bankSelector: gapBank,
      targetSelector: gapTargets,
      position: "right",
      className: "qti-choices-right",
    }),
  ),
  // Graphic gap matrix entries cover interaction-specific deltas; gap/match already
  // exercise all four qti-choices-* positions with the shared layout helper.
  entry(
    "graphic-gap-selections-light",
    "graphicGapMatch",
    "qti-selections-light",
    "stylesheet",
    graphicGapSelectionAssertions("qti-selections-light"),
  ),
  entry(
    "graphic-gap-selections-dark",
    "graphicGapMatch",
    "qti-selections-dark",
    "stylesheet",
    graphicGapSelectionAssertions("qti-selections-dark"),
  ),
  entry(
    "graphic-gap-choices-bottom",
    "graphicGapMatch",
    "qti-choices-bottom",
    "full",
    choicesPositionAssertions({
      interactionRoot: graphicGapRoot,
      layoutSelector: graphicGapLayout,
      bankSelector: graphicGapBank,
      targetSelector: graphicGapSurface,
      position: "bottom",
      className: "qti-choices-bottom",
    }),
  ),
  entry(
    "gap-placement-input-width",
    "gapMatch",
    ["qti-gap-placement", "qti-choices-left", "qti-input-width-10"],
    "full",
    [
      { type: "class-preserved", selector: gapRoot, className: "qti-gap-placement" },
      { type: "class-preserved", selector: gapRoot, className: "qti-choices-left" },
      { type: "class-preserved", selector: gapLayout, className: "qti3-gap-placement" },
      {
        type: "class-preserved",
        selector: `${gapLayout} .qti3-gap-passage`,
        className: "qti3-gap-placement",
      },
      {
        type: "attribute",
        selector: `${player} [data-gap-identifier="G2"]`,
        name: "data-qti-gap-input-width",
        value: "10",
      },
      {
        type: "computed-style-differs",
        firstSelector: `${player} [data-gap-identifier="G1"] button`,
        secondSelector: `${player} [data-gap-identifier="G2"] button`,
        property: "min-inline-size",
      },
    ],
  ),
];

export const sharedVocabularyManifest: SharedVocabularyManifestEntry[] = [
  ...interactionManifestEntries,
  ...contentManifestEntries,
];
