export {
  processQtiAdaptiveItemTurn,
  type QtiAdaptiveTurnInput,
  type QtiAdaptiveTurnResponseInput,
  type QtiAdaptiveTurnResult,
} from "./adaptive-turn.js";
export { assertNever } from "./assert-never.js";
export {
  createCatalogSupportResolution,
  type QtiCatalogSupportResolution,
  type QtiCatalogSupportResolutionOptions,
  type QtiResolvedCatalogReference,
  type QtiResolvedCatalogSupport,
} from "./catalog.js";
export {
  createCompanionMaterialsResolution,
  type QtiCompanionMaterialsResolution,
  type QtiCompanionMaterialsResolutionOptions,
  type QtiResolvedCompanionMaterialUnparsedChild,
  type QtiResolvedDigitalCompanionMaterial,
  type QtiResolvedPhysicalCompanionMaterial,
} from "./companion-materials-resolution.js";
export { isResolvableAssetUrl } from "./asset-url.js";
export {
  materializeQtiItemSubmission,
  type QtiItemSubmissionMaterializationInput,
  type QtiItemSubmissionMaterializationResult,
  type QtiItemSubmissionResponseInput,
  type QtiItemSubmissionScoringDisposition,
  type QtiVariableSnapshot,
} from "./item-submission-materialization.js";
export {
  prepareQtiDeliveryXml,
  type QtiDeliveryPreparationMode,
  type QtiDeliveryPreparationOptions,
  type QtiDeliveryPreparationResult,
} from "./delivery-preparation.js";
export {
  analyzeQtiDeliverySecurity,
  buildQtiDeliverySafeXml,
  type QtiDeliverySafeXmlResult,
  type QtiDeliverySecurityAnalysis,
  type QtiDeliverySecurityFinding,
  type QtiDeliverySecurityFindingKind,
} from "./delivery-security.js";
export { compileQtiPatternMask, isValidQtiPatternMask } from "./pattern-mask.js";
export {
  parseQtiPackageXmlTree,
  type QtiPackageXmlNode,
  type QtiPackageXmlTree,
} from "./package-xml.js";
export {
  decodeUtf8,
  parseQtiPackage,
  readQtiPackageZipEntries,
  type QtiAssessmentTestItemRef,
  type QtiAssessmentTestPackageModel,
  type QtiManifestFile,
  type QtiManifestResource,
  type QtiPackageAsset,
  type QtiPackageAssetSource,
  type QtiPackageEntry,
  type QtiPackageInflateContext,
  type QtiPackageInflateRaw,
  type QtiPackageItem,
  type QtiPackageItemSource,
  type QtiPackageParseOptions,
  type QtiPackageParseResult,
  type QtiPackageShape,
  type QtiStandardAlignment,
  type QtiTimingMetadata,
} from "./qti-package.js";
export { detectPackageMediaType } from "./qti-package-assets.js";
export { parseQtiXml } from "./parser.js";
export { numericTuple3, numericTuple4 } from "./parser-values.js";
export { isConformanceParseDiagnostic } from "./parse-diagnostics.js";
export {
  scoreQtiItemServerSide,
  type QtiServerScoringInput,
  type QtiServerScoringResponseInput,
  type QtiServerScoringResult,
} from "./server-scoring.js";
export {
  associationMaximumResponses,
  choiceMatchLimitExceeded,
  choiceMatchMaximum,
  directedPairChoiceUseCount,
  matchMaxDiagnostics,
  maximumAllowedResponses,
  maximumMediaPlays,
  maximumResponseDiagnostic,
  mediaPlayCount,
  minimumMediaPlays,
  minimumRequiredResponses,
  orderSubsetLimitsActive,
  parseUnlimitedMaximum,
  requiredResponseDiagnostic,
  responseCount,
  responseIsEmpty,
  responseLimitAttribute,
  responseValidationPolicy,
  wouldExceedChoiceMatchMaximum,
  type DirectedPairUseSide,
  type QtiResponseValidationPolicy,
} from "./response-validation-policy.js";
export {
  validateQtiResponseVariables,
  type QtiResponseValidationDiagnostic,
  type QtiResponseValidationDiagnosticCode,
  type QtiResponseValidationInput,
  type QtiResponseValidationResult,
  type QtiResponseVariableInput,
  type QtiResponseVariablesInput,
} from "./response-validation.js";
export {
  serializeResponseProcessing,
  type QtiSerializeResponseProcessingResult,
} from "./serializer-processing.js";
export {
  createTextToSpeechTraversal,
  parseQtiDataSsml,
  validateQtiDataSsmlMetadata,
  type QtiDataSsml,
  type QtiDataSsmlBreak,
  type QtiDataSsmlBreakStrength,
  type QtiDataSsmlParseResult,
  type QtiDataSsmlPhoneme,
  type QtiDataSsmlProsody,
  type QtiDataSsmlSayAs,
  type QtiDataSsmlSub,
  type QtiTextToSpeechSegment,
  type QtiTextToSpeechSegmentKind,
  type QtiTextToSpeechTraversal,
} from "./tts.js";
export {
  assertQtiAttemptStateV1,
  createItemSession,
  isQtiAttemptStateV1,
  visibleModalFeedback,
  type QtiCustomOperatorContext,
  type QtiCustomOperatorHandler,
  type QtiCustomOperatorRegistry,
  type QtiItemSession,
  type QtiItemSessionOptions,
} from "./session.js";
export {
  deprecatedInteractionSupport,
  elementSupport,
  getInteractionSupport,
  interactionRegistryStatus,
  interactionNameToType,
  interactionSupport,
  itemMetadataSupport,
  processingSupport,
} from "./support.js";
export { sharedVocabularyClassSupport } from "./shared-vocabulary-support.js";
export {
  findSharedVocabularyCoverageViolations,
  type SharedVocabularyCoverageViolation,
} from "./shared-vocabulary-coverage-policy.js";
export {
  describeSharedVocabularyPrecedence,
  formatSharedVocabularyClassValueRange,
  matchedSharedVocabularyClassNames,
  parseClassValue,
  parsePositiveNumber,
  parseSharedVocabularyAttributes,
  parseSharedVocabularyClasses,
  serializeSharedVocabularyAttributes,
  serializeSharedVocabularyClassNames,
  sharedVocabularyClassNamesForField,
  sharedVocabularyFieldById,
  sharedVocabularyFieldsForInteraction,
  sharedVocabularyFixedClassName,
  sharedVocabularyInteractionFields,
  type QtiSharedVocabularyAttributeValueType,
  type QtiSharedVocabularyField,
  type QtiSharedVocabularyFieldValue,
  type QtiSharedVocabularyState,
  type QtiSharedVocabularyStateValue,
} from "./shared-vocabulary-authoring.js";
export {
  SHARED_VOCABULARY_CHOICE_AND_ORDER_INTERACTIONS,
  SHARED_VOCABULARY_CHOICE_INTERACTIONS,
  SHARED_VOCABULARY_CHOICES_LAYOUT_INTERACTIONS,
  SHARED_VOCABULARY_MEDIA_INTERACTIONS,
  SHARED_VOCABULARY_SELECTION_PRESENTATION_INTERACTIONS,
} from "./shared-vocabulary-interaction-sets.js";
export {
  matrixCoverageFamilyForClass,
  SHARED_VOCABULARY_CHOICE_WRITING_ORIENTATIONS,
  SHARED_VOCABULARY_CONTENT_ALIGNMENTS,
  SHARED_VOCABULARY_CONTENT_FLOAT_SUFFIXES,
  SHARED_VOCABULARY_CONTENT_LIST_STYLE_TYPES,
  SHARED_VOCABULARY_CONTENT_TEXT_INDENT_SUFFIXES,
  SHARED_VOCABULARY_CONTENT_VALIGNS,
  SHARED_VOCABULARY_CONTENT_WIDTH_ALIASES,
  SHARED_VOCABULARY_CONTENT_WRITING_MODES,
  SHARED_VOCABULARY_LAYOUT_COLUMN_SPAN_COUNT,
  SHARED_VOCABULARY_LAYOUT_OFFSET_COUNT,
  sharedVocabularyMatrixCoverageFamilies,
} from "./shared-vocabulary-generated-families.js";
export {
  isEnforcedSharedVocabularyLevel,
  type SharedVocabularySupportLevel,
} from "./shared-vocabulary-levels.js";
export {
  extendedTextCounterPosition,
  extendedTextCounterPositionFromAttributes,
  extendedTextCounterState,
  extendedTextCounterStateFromAttributes,
  extendedTextCounterValues,
  extendedTextExpectedLengthFromAttributes,
  extendedTextHeightLines,
  extendedTextHeightLinesFromAttributes,
  firstMatchingSharedVocabularyClass,
  formatSupportedExtendedTextCounterClasses,
  formatSupportedExtendedTextHeightLinesClasses,
  formatSupportedGapInputWidthClasses,
  formatSupportedInputWidthClasses,
  formatSupportedMediaPlayerControlsTokens,
  gapInputWidthFromAttributes,
  isSupportedExtendedTextCounterClassName,
  isSupportedExtendedTextHeightLinesClassName,
  inputWidthFromAttributes,
  isSupportedInputWidthClassName,
  isSupportedMediaPlayerControlsToken,
  mediaPlayerControlsTokens,
  SHARED_VOCABULARY_CHOICES_POSITIONS,
  SHARED_VOCABULARY_CHOICES_STACKING,
  SHARED_VOCABULARY_EXTENDED_TEXT_COUNTER_CLASSES,
  SHARED_VOCABULARY_EXTENDED_TEXT_HEIGHT_LINES,
  SHARED_VOCABULARY_GAP_INPUT_WIDTHS,
  SHARED_VOCABULARY_INPUT_WIDTHS,
  SHARED_VOCABULARY_LABEL_STYLES,
  SHARED_VOCABULARY_LABEL_SUFFIXES,
  SHARED_VOCABULARY_MEDIA_PLAYER_CONTROLS,
  SHARED_VOCABULARY_ORIENTATIONS,
  SHARED_VOCABULARY_SELECTION_TONES,
  sharedVocabularyClassNames,
  supportedExtendedTextCounterClassNames,
  supportedExtendedTextHeightLinesClassNames,
  supportedGapInputWidthClassNames,
  supportedInputWidthClassNames,
  unsupportedMediaPlayerControlsTokens,
  type ExtendedTextCounterState,
  type SharedVocabularyExtendedTextCounterPosition,
  type SharedVocabularyMediaPlayerControls,
} from "./shared-vocabulary.js";
export { validateAssessmentItem } from "./validation.js";
export type {
  QtiAssessmentItem,
  QtiAttemptStatus,
  QtiAttemptStateV1,
  QtiCatalog,
  QtiCatalogCard,
  QtiCatalogCardEntry,
  QtiCatalogFileHref,
  QtiCatalogHtmlContent,
  QtiCatalogInfo,
  QtiCatalogReference,
  QtiChoice,
  QtiChoiceRole,
  QtiCompanionMaterialsInfo,
  QtiCompanionMaterialsUnparsedChild,
  QtiContentNode,
  QtiCustomInteractionDefinition,
  QtiDigitalMaterial,
  QtiInteractionMarkupDefinition,
  QtiDiagnostic,
  QtiDocument,
  QtiElementSupport,
  QtiInteractionElementSupport,
  QtiItemMetadataElementSupport,
  QtiInteraction,
  QtiInteractionRegistryStatus,
  QtiInteractionType,
  QtiMediaSource,
  QtiMediaTrack,
  QtiMapEntry,
  QtiModalFeedback,
  QtiObjectAsset,
  QtiOutcomeDeclaration,
  QtiParseResult,
  QtiPhysicalMaterial,
  QtiProcessingExpression,
  QtiProcessingElementSupport,
  QtiPortableCustomDefinition,
  QtiPortableCustomInteractionModule,
  QtiPortableCustomInteractionModules,
  QtiPortableCustomStateValue,
  QtiPortableCustomVariableBinding,
  QtiAreaMapEntry,
  QtiGapMatchGapSegment,
  QtiGapMatchSegment,
  QtiGapMatchTextSegment,
  QtiHottextChoiceSegment,
  QtiHottextSegment,
  QtiHottextTextSegment,
  QtiResponseBranch,
  QtiResponseCondition,
  QtiResponseDeclaration,
  QtiResponseProcessing,
  QtiResponseRule,
  QtiScoreResult,
  QtiStylesheet,
  QtiLookupOutcomeValue,
  QtiSetOutcomeValue,
  QtiSupportStatus,
  QtiTemplateDeclaration,
  QtiTemplateBranch,
  QtiTemplateProcessing,
  QtiTemplateRule,
  QtiValidationResult,
  QtiValue,
  SharedVocabularyClassSupport,
} from "./types.js";
export {
  isQtiPortableCustomStateValue,
  isQtiValue,
  qtiScalarToString,
  qtiValueToIdentifierList,
  qtiValueToString,
  qtiValueToStringList,
  readQtiPortableCustomStateValue,
  readQtiJsonValue,
  unknownToDisplayString,
} from "./value-format.js";
