export { parseQtiXml } from "./parser.js";
export {
  createTextToSpeechTraversal,
  parseQtiDataSsml,
  validateQtiDataSsmlMetadata,
  type QtiDataSsml,
  type QtiDataSsmlBreak,
  type QtiDataSsmlBreakStrength,
  type QtiDataSsmlParseResult,
  type QtiDataSsmlPhoneme,
  type QtiDataSsmlProsody,
  type QtiDataSsmlSayAs,
  type QtiDataSsmlSub,
  type QtiTextToSpeechSegment,
  type QtiTextToSpeechSegmentKind,
  type QtiTextToSpeechTraversal,
} from "./tts.js";
export {
  assertQtiAttemptStateV1,
  createItemSession,
  isQtiAttemptStateV1,
  visibleModalFeedback,
  type QtiCustomOperatorContext,
  type QtiCustomOperatorHandler,
  type QtiCustomOperatorRegistry,
  type QtiItemSession,
  type QtiItemSessionOptions,
} from "./session.js";
export {
  deprecatedInteractionSupport,
  elementSupport,
  getInteractionSupport,
  interactionNameToType,
  interactionSupport,
  processingSupport,
} from "./support.js";
export { validateAssessmentItem } from "./validation.js";
export type {
  QtiAssessmentItem,
  QtiAttemptStatus,
  QtiAttemptStateV1,
  QtiChoice,
  QtiChoiceRole,
  QtiContentNode,
  QtiDiagnostic,
  QtiDocument,
  QtiElementSupport,
  QtiInteractionElementSupport,
  QtiInteraction,
  QtiInteractionType,
  QtiMediaSource,
  QtiMediaTrack,
  QtiModalFeedback,
  QtiObjectAsset,
  QtiParseResult,
  QtiProcessingElementSupport,
  QtiPortableCustomDefinition,
  QtiPortableCustomInteractionModule,
  QtiPortableCustomInteractionModules,
  QtiPortableCustomStateValue,
  QtiPortableCustomVariableBinding,
  QtiResponseBranch,
  QtiScoreResult,
  QtiSupportStatus,
  QtiTemplateDeclaration,
  QtiTemplateBranch,
  QtiTemplateProcessing,
  QtiTemplateRule,
  QtiValidationResult,
  QtiValue,
} from "./types.js";
