export {
  createCatalogSupportResolution,
  type QtiCatalogSupportResolution,
  type QtiCatalogSupportResolutionOptions,
  type QtiResolvedCatalogReference,
  type QtiResolvedCatalogSupport,
} from "./catalog.js";
export {
  analyzeQtiDeliverySecurity,
  buildQtiDeliverySafeXml,
  type QtiDeliverySafeXmlResult,
  type QtiDeliverySecurityAnalysis,
  type QtiDeliverySecurityFinding,
  type QtiDeliverySecurityFindingKind,
} from "./delivery-security.js";
export { parseQtiXml } from "./parser.js";
export {
  scoreQtiItemServerSide,
  type QtiServerScoringInput,
  type QtiServerScoringResponseInput,
  type QtiServerScoringResult,
} from "./server-scoring.js";
export {
  createTextToSpeechTraversal,
  parseQtiDataSsml,
  validateQtiDataSsmlMetadata,
  type QtiDataSsml,
  type QtiDataSsmlBreak,
  type QtiDataSsmlBreakStrength,
  type QtiDataSsmlParseResult,
  type QtiDataSsmlPhoneme,
  type QtiDataSsmlProsody,
  type QtiDataSsmlSayAs,
  type QtiDataSsmlSub,
  type QtiTextToSpeechSegment,
  type QtiTextToSpeechSegmentKind,
  type QtiTextToSpeechTraversal,
} from "./tts.js";
export {
  assertQtiAttemptStateV1,
  createItemSession,
  isQtiAttemptStateV1,
  visibleModalFeedback,
  type QtiCustomOperatorContext,
  type QtiCustomOperatorHandler,
  type QtiCustomOperatorRegistry,
  type QtiItemSession,
  type QtiItemSessionOptions,
} from "./session.js";
export {
  deprecatedInteractionSupport,
  elementSupport,
  getInteractionSupport,
  interactionNameToType,
  interactionSupport,
  processingSupport,
} from "./support.js";
export {
  formatSupportedGapInputWidthClasses,
  formatSupportedInputWidthClasses,
  gapInputWidthFromAttributes,
  inputWidthFromAttributes,
  isSupportedInputWidthClassName,
  SHARED_VOCABULARY_GAP_INPUT_WIDTHS,
  SHARED_VOCABULARY_INPUT_WIDTHS,
  sharedVocabularyClassNames,
  supportedGapInputWidthClassNames,
  supportedInputWidthClassNames,
} from "./shared-vocabulary.js";
export { validateAssessmentItem } from "./validation.js";
export type {
  QtiAssessmentItem,
  QtiAttemptStatus,
  QtiAttemptStateV1,
  QtiCatalog,
  QtiCatalogCard,
  QtiCatalogCardEntry,
  QtiCatalogFileHref,
  QtiCatalogHtmlContent,
  QtiCatalogInfo,
  QtiCatalogReference,
  QtiChoice,
  QtiChoiceRole,
  QtiContentNode,
  QtiDiagnostic,
  QtiDocument,
  QtiElementSupport,
  QtiInteractionElementSupport,
  QtiInteraction,
  QtiInteractionType,
  QtiMediaSource,
  QtiMediaTrack,
  QtiModalFeedback,
  QtiObjectAsset,
  QtiParseResult,
  QtiProcessingElementSupport,
  QtiPortableCustomDefinition,
  QtiPortableCustomInteractionModule,
  QtiPortableCustomInteractionModules,
  QtiPortableCustomStateValue,
  QtiPortableCustomVariableBinding,
  QtiResponseBranch,
  QtiScoreResult,
  QtiSupportStatus,
  QtiTemplateDeclaration,
  QtiTemplateBranch,
  QtiTemplateProcessing,
  QtiTemplateRule,
  QtiValidationResult,
  QtiValue,
} from "./types.js";
export {
  isQtiPortableCustomStateValue,
  isQtiValue,
  qtiScalarToString,
  qtiValueToIdentifierList,
  qtiValueToString,
  qtiValueToStringList,
  readQtiPortableCustomStateValue,
  readQtiJsonValue,
  unknownToDisplayString,
} from "./value-format.js";
