import { describe, expect, it } from "vitest";
import type {
  QtiAreaMapEntry,
  QtiGapMatchGapSegment,
  QtiGapMatchSegment,
  QtiGapMatchTextSegment,
  QtiHottextChoiceSegment,
  QtiHottextSegment,
  QtiHottextTextSegment,
  QtiLookupOutcomeValue,
  QtiAssessmentTestPackageModel,
  QtiDeliveryPreparationMode,
  QtiDeliveryPreparationOptions,
  QtiDeliveryPreparationResult,
  QtiItemSubmissionMaterializationInput,
  QtiItemSubmissionMaterializationResult,
  QtiItemSubmissionScoringDisposition,
  QtiVariableSnapshot,
  QtiManifestResource,
  QtiMapEntry,
  QtiOutcomeDeclaration,
  QtiPackageAsset,
  QtiPackageItem,
  QtiPackageParseResult,
  QtiProcessingExpression,
  QtiResponseValidationDiagnostic,
  QtiResponseValidationDiagnosticCode,
  QtiResponseValidationInput,
  QtiResponseValidationResult,
  QtiResponseBranch,
  QtiResponseCondition,
  QtiResponseDeclaration,
  QtiResponseProcessing,
  QtiResponseRule,
  QtiSetOutcomeValue,
  QtiStandardAlignment,
  QtiTimingMetadata,
} from "./index.js";

type PublicParserModelTypes = [
  QtiResponseDeclaration,
  QtiOutcomeDeclaration,
  QtiMapEntry,
  QtiAreaMapEntry,
  QtiResponseProcessing,
  QtiResponseCondition,
  QtiResponseBranch,
  QtiResponseRule,
  QtiSetOutcomeValue,
  QtiLookupOutcomeValue,
  QtiProcessingExpression,
  QtiHottextSegment,
  QtiHottextTextSegment,
  QtiHottextChoiceSegment,
  QtiGapMatchSegment,
  QtiGapMatchTextSegment,
  QtiGapMatchGapSegment,
  QtiDeliveryPreparationMode,
  QtiDeliveryPreparationOptions,
  QtiDeliveryPreparationResult,
  QtiItemSubmissionMaterializationInput,
  QtiItemSubmissionMaterializationResult,
  QtiItemSubmissionScoringDisposition,
  QtiVariableSnapshot,
  QtiPackageParseResult,
  QtiPackageItem,
  QtiPackageAsset,
  QtiManifestResource,
  QtiAssessmentTestPackageModel,
  QtiTimingMetadata,
  QtiStandardAlignment,
  QtiResponseValidationDiagnostic,
  QtiResponseValidationDiagnosticCode,
  QtiResponseValidationInput,
  QtiResponseValidationResult,
];

const typeExportsCompile: PublicParserModelTypes | undefined = undefined;

describe("public parser model type exports", () => {
  it("exposes parser model types from the core entrypoint", () => {
    expect(typeExportsCompile).toBeUndefined();
  });
});
