import { describe, expect, it } from "vitest";
import { createItemSession, parseQtiXml, validateAssessmentItem, type QtiValue } from "./index.js";

// Oracles: QTI 3 §2.2.2 (NULL), §7.21 (typed map keys), and the published
// https://purl.imsglobal.org/spec/qti/v3p0/rptemplates/map_response.xml
// /map_response_point.xml algorithms. Synthetic XML; expected scores are not generated by writers.
function session(declaration: string, processing: string, body = "<p>Evaluate the response.</p>") {
  const parsed =
    parseQtiXml(`<qti-assessment-item xmlns="http://www.imsglobal.org/xsd/imsqtiasi_v3p0" identifier="contracts" title="Scoring contracts" time-dependent="false">
    ${declaration}<qti-outcome-declaration identifier="SCORE" cardinality="single" base-type="float"/>
    <qti-outcome-declaration identifier="RESULT" cardinality="single" base-type="boolean"/>
    <qti-item-body>${body}</qti-item-body>${processing}</qti-assessment-item>`);
  expect(parsed.diagnostics).toEqual([]);
  if (!parsed.document) throw new Error("Expected valid item");
  expect(validateAssessmentItem(parsed.document).diagnostics).toEqual([]);
  return createItemSession(parsed.document);
}

describe("spec scoring contracts", () => {
  for (const point of [false, true]) {
    for (const bound of ['lower-bound="2"', 'upper-bound="-2"']) {
      it(`matches the standard ${point ? "point" : "value"} template NULL branch with ${bound}`, () => {
        const operator = point ? "map-response-point" : "map-response";
        const declaration = `<qti-response-declaration identifier="RESPONSE" cardinality="multiple" base-type="${point ? "point" : "identifier"}">
          ${point ? `<qti-area-mapping default-value="0" ${bound}><qti-area-map-entry shape="rect" coords="0,0,20,20" mapped-value="5"/></qti-area-mapping>` : `<qti-mapping default-value="0" ${bound}><qti-map-entry map-key="A" mapped-value="5"/></qti-mapping>`}</qti-response-declaration>`;
        const body = point
          ? '<qti-select-point-interaction response-identifier="RESPONSE" max-choices="0"><img src="image.png" width="100" height="100" alt="Select a point"/></qti-select-point-interaction>'
          : '<qti-choice-interaction response-identifier="RESPONSE" max-choices="0"><qti-simple-choice identifier="A">A</qti-simple-choice><qti-simple-choice identifier="B">B</qti-simple-choice></qti-choice-interaction>';
        const builtin = session(
          declaration,
          `<qti-response-processing template="https://purl.imsglobal.org/spec/qti/v3p0/rptemplates/${point ? "map_response_point" : "map_response"}.xml"/>`,
          body,
        );
        const explicit = session(
          declaration,
          `<qti-response-processing><qti-response-condition><qti-response-if>
          <qti-is-null><qti-variable identifier="RESPONSE"/></qti-is-null>
          <qti-set-outcome-value identifier="SCORE"><qti-base-value base-type="float">0</qti-base-value></qti-set-outcome-value>
          </qti-response-if><qti-response-else><qti-set-outcome-value identifier="SCORE"><qti-${operator} identifier="RESPONSE"/></qti-set-outcome-value></qti-response-else></qti-response-condition></qti-response-processing>`,
          body,
        );
        const direct = session(
          declaration,
          `<qti-response-processing><qti-set-outcome-value identifier="SCORE"><qti-${operator} identifier="RESPONSE"/></qti-set-outcome-value></qti-response-processing>`,
          body,
        );
        for (const unanswered of [null, []]) {
          direct.respond("RESPONSE", unanswered);
          expect(direct.score().outcomes.SCORE).toBe(bound.startsWith("lower") ? 2 : -2);
        }
        for (const response of [null, [], [point ? "10 10" : "A"]]) {
          builtin.respond("RESPONSE", response);
          explicit.respond("RESPONSE", response);
          const expected =
            response === null || response.length === 0 ? 0 : bound.startsWith("lower") ? 5 : -2;
          expect(explicit.score().outcomes.SCORE).toBe(expected);
          expect(builtin.score().outcomes.SCORE).toBe(expected);
        }
      });
    }
  }

  it.each([
    ["integer", "01", 1],
    ["integer", "+01", 1],
    ["integer", "-00", 0],
    ["float", "1.0", 1],
    ["float", "1e0", 1],
    ["boolean", "1", true],
    ["boolean", "0", false],
    ["pair", "B A", "A B"],
    ["directedPair", "A B", "A B"],
    ["string", "01", "01"],
  ] satisfies Array<[string, string, QtiValue]>)(
    "maps %s key %s by value",
    (type, key, response) => {
      const item = session(
        `<qti-response-declaration identifier="R" cardinality="single" base-type="${type}"><qti-mapping default-value="-1"><qti-map-entry map-key="${key}" mapped-value="5"/></qti-mapping></qti-response-declaration>`,
        `<qti-response-processing><qti-set-outcome-value identifier="SCORE"><qti-map-response identifier="R"/></qti-set-outcome-value></qti-response-processing>`,
      );
      item.respond("R", response);
      expect(item.score().outcomes.SCORE).toBe(5);
    },
  );

  it.each(["match", 'string-match case-sensitive="true"', 'substring case-sensitive="true"'])(
    "propagates NULL through %s",
    (operator) => {
      const name = operator.split(" ")[0];
      const item = session(
        '<qti-response-declaration identifier="R" cardinality="single" base-type="string"/>',
        `<qti-response-processing><qti-set-outcome-value identifier="RESULT"><qti-${operator}><qti-variable identifier="R"/><qti-variable identifier="R"/></qti-${name}></qti-set-outcome-value></qti-response-processing>`,
      );
      for (const value of [null, "", "A", " "]) {
        item.respond("R", value);
        expect(item.score().outcomes.RESULT).toBe(value === null || value === "" ? null : true);
      }
    },
  );

  it.each(["multiple", "ordered"])(
    "treats empty %s containers as NULL, preserving nonempty ones",
    (cardinality) => {
      const item = session(
        `<qti-response-declaration identifier="R" cardinality="${cardinality}" base-type="identifier"/>`,
        '<qti-response-processing><qti-set-outcome-value identifier="RESULT"><qti-match><qti-variable identifier="R"/><qti-variable identifier="R"/></qti-match></qti-set-outcome-value></qti-response-processing>',
      );
      for (const value of [null, [], ["A"]]) {
        item.respond("R", value);
        expect(item.score().outcomes.RESULT).toBe(
          value === null || value.length === 0 ? null : true,
        );
      }
    },
  );
});

describe("mapping value distinctions", () => {
  it.each([
    ["string", "01", "1"],
    ["directedPair", "A B", "B A"],
    ["boolean", "1", false],
  ] satisfies Array<[string, string, QtiValue]>)(
    "keeps distinct %s mapping values distinct",
    (type, key, response) => {
      const item = session(
        `<qti-response-declaration identifier="R" cardinality="single" base-type="${type}"><qti-mapping default-value="-1"><qti-map-entry map-key="${key}" mapped-value="5"/></qti-mapping></qti-response-declaration>`,
        '<qti-response-processing><qti-set-outcome-value identifier="SCORE"><qti-map-response identifier="R"/></qti-set-outcome-value></qti-response-processing>',
      );
      item.respond("R", response);
      expect(item.score().outcomes.SCORE).toBe(-1);
    },
  );

  it("treats an empty string as NULL even for direct variable mapping", () => {
    const item = session(
      '<qti-response-declaration identifier="R" cardinality="single" base-type="string"><qti-mapping default-value="-1"><qti-map-entry map-key="A" mapped-value="5"/></qti-mapping></qti-response-declaration>',
      '<qti-response-processing><qti-set-outcome-value identifier="SCORE"><qti-map-response identifier="R"/></qti-set-outcome-value></qti-response-processing>',
    );
    for (const response of [null, ""]) {
      item.respond("R", response);
      expect(item.score().outcomes.SCORE).toBe(0);
    }
    item.respond("R", " ");
    expect(item.score().outcomes.SCORE).toBe(-1);
  });
});
