import type { PlayerMessageCatalog } from "./player-message-catalog.js";

/** English player chrome catalog (JSON-serializable). Hosts copy this shape for locale files. */
export const defaultPlayerMessageCatalog: PlayerMessageCatalog = {
  locale: "en",
  directions: {
    up: "up",
    down: "down",
    left: "left",
    right: "right",
  },
  interactionTypes: {
    associate: "Associate",
    choice: "Choice",
    drawing: "Drawing",
    endAttempt: "End attempt",
    extendedText: "Extended text",
    gapMatch: "Gap match",
    graphicAssociate: "Graphic associate",
    graphicGapMatch: "Graphic gap match",
    graphicOrder: "Graphic order",
    hottext: "Hot text",
    hotspot: "Hotspot",
    inlineChoice: "Inline choice",
    match: "Match",
    media: "Media",
    order: "Order",
    pair: "Pair",
    portableCustom: "Portable custom",
    positionObject: "Position object",
    selectPoint: "Select point",
    slider: "Slider",
    textEntry: "Text entry",
    upload: "Upload",
  },
  strings: {
    remove: "Remove",
    removePair: "Remove {label}",
    clearDrawing: "Clear drawing",
    clearPoints: "Clear points",
    endAttempt: "End attempt",
    uploadResponse: "Upload response",
    movableObject: "Movable object",
    placeObject: "Place",
    inlineChoicePrompt: "Choose...",
    extendedTextCounter: "{characters} {characterUnit}, {words} {wordUnit}",
    "characterUnit.one": "character",
    "characterUnit.other": "characters",
    "wordUnit.one": "word",
    "wordUnit.other": "words",
    hotspotSelectionSummary: "Selected {selection}",
    noPointSelected: "No point selected",
    noRegionSelected: "No region selected",
    noAssociationsMade: "No associations made",
    "associationsMade.one": "{count} association made.",
    "associationsMade.other": "{count} associations made.",
    associationPairLabel: "{source} to {target}",
    hotspotSelectedChooseAnother: "{label} selected. Choose another hotspot.",
    moveChoice: "Move {label} {direction}",
    movePoint: "Move point {direction}",
    moveObject: "Move object {direction}",
    matchSourcesBank: "Match sources",
    matchTargetsBank: "Match targets",
    matchSelectedPairsList: "Match selected pairs",
    interactionSourcesBank: "{typeName} sources",
    interactionTargetsBank: "{typeName} targets",
    interactionSelectedPairsList: "{typeName} selected pairs",
    associateFirstConceptRegion: "First concept",
    associatePairWithRegion: "Pair with",
    matchPromptRegion: "Prompt",
    matchMatchRegion: "Match",
    genericSourceRegion: "Source",
    genericTargetRegion: "Target",
    interactionHotspots: "{typeName} hotspots",
    interactionImageAlt: "{typeName} image",
    interactionCurrentOrderList: "{typeName} current order",
    interactionSelectedOrderList: "{typeName} selected order",
    interactionChoicesBank: "{typeName} choices",
    interactionGapTargets: "{typeName} targets",
    interactionTargetImage: "{typeName} target image",
    interactionOptionsList: "{typeName} options",
    interactionCoordinateResponse: "{typeName} coordinate response",
    interactionCoordinateArea: "{typeName} coordinate area",
    interactionCoordinateAreaSelected: "{typeName} coordinate area, selected {coordinates}",
    interactionPlacementResponse: "{typeName} object placement response",
    interactionPlacementStage: "{typeName} placement stage",
    interactionPlacementStageEmpty: "{typeName} placement stage, object not placed",
    interactionPlacementStageAt: "{typeName} placement stage, object at {coordinates}",
    interactionDrawingResponse: "{typeName} response",
    drawingSurface: "Drawing response surface",
    drawingSurfaceEmpty: "Drawing response surface, no strokes",
    "drawingSurfaceStrokeCount.one": "Drawing response surface, {count} stroke",
    "drawingSurfaceStrokeCount.other": "Drawing response surface, {count} strokes",
    drawingStatusEmpty: "No drawing strokes.",
    "drawingStatusStrokeCount.one": "{count} drawing stroke.",
    "drawingStatusStrokeCount.other": "{count} drawing strokes.",
    gapLabel: "Gap {index}",
    graphicGapTargetLabel: "Target {index}",
    gapEmptyState: "{label}, empty",
    gapAssignedState: "{label}, assigned {assigned}",
    "gapLabelsPlacedCount.one": "{count} label placed.",
    "gapLabelsPlacedCount.other": "{count} labels placed.",
    gapNoLabelsPlaced: "No labels placed.",
    orderedItemAtPosition: "{label}, position {position} of {total}",
    orderedItemMovedOneStep: "{label} moved {direction}.",
    orderedItemMovedToPosition: "{label} moved to position {position} of {total}.",
    "graphicOrderRegionsSelected.one": "{count} region ordered.",
    "graphicOrderRegionsSelected.other": "{count} regions ordered.",
    graphicOrderNoRegionsSelected: "No regions ordered.",
    objectNotPlaced: "Object not placed",
    objectPositionedAt: "Object positioned at {coordinates}",
    selectedPointAt: "Selected point {coordinates}",
    "selectedPointsSummary.one": "{count} selected point: {coordinates}",
    "selectedPointsSummary.other": "{count} selected points: {coordinates}",
    extendedTextResponseLabel: "Extended text response",
    textResponseLabel: "Text response",
    sliderResponseLabel: "Slider response",
  },
};
